# 04-nginx-deployment.yaml
apiVersion: apps/v1
kind: DeployMent
metadata:
  name: nginx
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    sepc:
      containers:
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        livenessProbe:
          exec:
            command: ["nginx", "-t"]
          initialDelaySeconds: 10
          perioSeconds: 60
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          perioSeconds: 5
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
        
---
# Nginx配置(ConfigMap)
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: wordpress
data:
  default.conf: |
    server {
      listen 80;
      server_name k8sapi.hebin.com;
      location / {
        proxy_pass http://wordpress;
        proxy_set_header Host  $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }

---
# 对外暴露Nginx服务(Service)
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: wordpress
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - prot: 80
    targetPort: 80
    